//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.ComponentModel;

namespace EduEnginee.Models
{
    public partial class QuestionDefinition
    {
        public QuestionDefinition()
        {
            this.QuizAnswers = new HashSet<QuizAnswer>();
        }
    
        public int Id { get; set; }
        public string QuestionData { get; set; }
        public string QuestionTypeName { get; set; }
        [DisplayName("Sl.")]
        public int SortOrder { get; set; }
        public int QuizDefinitionKey { get; set; }
        public string QuestionText { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Option5 { get; set; }
        public string Option6 { get; set; }
        public int CorrectAns { get; set; }
        public string CorrectAnsText
        {
            get
            {
                if (CorrectAns==1)
                {
                    return Option1;
                }
                else if (CorrectAns == 2)
                {
                    return Option2;
                }
                else if (CorrectAns == 3)
                {
                    return Option3;
                }
                else if (CorrectAns == 4)
                {
                    return Option4;
                }
                else if (CorrectAns == 5)
                {
                    return Option5;
                }
                else if (CorrectAns == 6)
                {
                    return Option6;
                }
                return "";

    
            }
            
        }
        public string Explanation { get; set; }
    
        public virtual QuizDefinition QuizDefinition { get; set; }
        public virtual ICollection<QuizAnswer> QuizAnswers { get; set; }
    }
    
}
