//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace EduEnginee.Models
{
    public partial class QuizDbEntities : DbContext
    {
        public QuizDbEntities()
            : base("name=QuizDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<QuestionDefinition> QuestionDefinitions { get; set; }
        public DbSet<QuizAnswer> QuizAnswers { get; set; }
        public DbSet<QuizDefinition> QuizDefinitions { get; set; }
        public DbSet<Quizze> Quizzes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
