//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QuizDbModel", "FK_QuestionDefinitions_Quiz_GiveAQuizModel_QuizDefinitions1", "QuizDefinitions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduEnginee.Models.QuizDefinition), "QuestionDefinitions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Models.QuestionDefinition), true)]
[assembly: EdmRelationshipAttribute("QuizDbModel", "FK_QuizAnswers_QuestionDefinitions", "QuestionDefinitions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduEnginee.Models.QuestionDefinition), "QuizAnswers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Models.QuizAnswer), true)]
[assembly: EdmRelationshipAttribute("QuizDbModel", "FK_QuizAnswers_Quizzes", "Quizzes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EduEnginee.Models.Quizze), "QuizAnswers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Models.QuizAnswer), true)]
[assembly: EdmRelationshipAttribute("QuizDbModel", "FK_Quizzes_QuizDefinition_GiveAQuizModel_QuizDefinitions", "QuizDefinitions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduEnginee.Models.QuizDefinition), "Quizzes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Models.Quizze), true)]

#endregion

namespace EduEnginee.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuizDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuizDbEntities object using the connection string found in the 'QuizDbEntities' section of the application configuration file.
        /// </summary>
        public QuizDbEntities() : base("name=QuizDbEntities", "QuizDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuizDbEntities object.
        /// </summary>
        public QuizDbEntities(string connectionString) : base(connectionString, "QuizDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuizDbEntities object.
        /// </summary>
        public QuizDbEntities(EntityConnection connection) : base(connection, "QuizDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuestionDefinition> QuestionDefinitions
        {
            get
            {
                if ((_QuestionDefinitions == null))
                {
                    _QuestionDefinitions = base.CreateObjectSet<QuestionDefinition>("QuestionDefinitions");
                }
                return _QuestionDefinitions;
            }
        }
        private ObjectSet<QuestionDefinition> _QuestionDefinitions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuizAnswer> QuizAnswers
        {
            get
            {
                if ((_QuizAnswers == null))
                {
                    _QuizAnswers = base.CreateObjectSet<QuizAnswer>("QuizAnswers");
                }
                return _QuizAnswers;
            }
        }
        private ObjectSet<QuizAnswer> _QuizAnswers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuizDefinition> QuizDefinitions
        {
            get
            {
                if ((_QuizDefinitions == null))
                {
                    _QuizDefinitions = base.CreateObjectSet<QuizDefinition>("QuizDefinitions");
                }
                return _QuizDefinitions;
            }
        }
        private ObjectSet<QuizDefinition> _QuizDefinitions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Quizze> Quizzes
        {
            get
            {
                if ((_Quizzes == null))
                {
                    _Quizzes = base.CreateObjectSet<Quizze>("Quizzes");
                }
                return _Quizzes;
            }
        }
        private ObjectSet<Quizze> _Quizzes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuestionDefinitions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestionDefinitions(QuestionDefinition questionDefinition)
        {
            base.AddObject("QuestionDefinitions", questionDefinition);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuizAnswers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuizAnswers(QuizAnswer quizAnswer)
        {
            base.AddObject("QuizAnswers", quizAnswer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuizDefinitions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuizDefinitions(QuizDefinition quizDefinition)
        {
            base.AddObject("QuizDefinitions", quizDefinition);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Quizzes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuizzes(Quizze quizze)
        {
            base.AddObject("Quizzes", quizze);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuizDbModel", Name="QuestionDefinition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuestionDefinition : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuestionDefinition object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="questionData">Initial value of the QuestionData property.</param>
        /// <param name="questionTypeName">Initial value of the QuestionTypeName property.</param>
        /// <param name="sortOrder">Initial value of the SortOrder property.</param>
        /// <param name="quizDefinitionKey">Initial value of the QuizDefinitionKey property.</param>
        /// <param name="option1">Initial value of the Option1 property.</param>
        /// <param name="option2">Initial value of the Option2 property.</param>
        /// <param name="option3">Initial value of the Option3 property.</param>
        /// <param name="option4">Initial value of the Option4 property.</param>
        /// <param name="option5">Initial value of the Option5 property.</param>
        /// <param name="option6">Initial value of the Option6 property.</param>
        /// <param name="correctAns">Initial value of the CorrectAns property.</param>
        /// <param name="explanation">Initial value of the Explanation property.</param>
        public static QuestionDefinition CreateQuestionDefinition(global::System.Int32 id, global::System.String questionData, global::System.String questionTypeName, global::System.Int32 sortOrder, global::System.Int32 quizDefinitionKey, global::System.String option1, global::System.String option2, global::System.String option3, global::System.String option4, global::System.String option5, global::System.String option6, global::System.Int32 correctAns, global::System.String explanation)
        {
            QuestionDefinition questionDefinition = new QuestionDefinition();
            questionDefinition.Id = id;
            questionDefinition.QuestionData = questionData;
            questionDefinition.QuestionTypeName = questionTypeName;
            questionDefinition.SortOrder = sortOrder;
            questionDefinition.QuizDefinitionKey = quizDefinitionKey;
            questionDefinition.Option1 = option1;
            questionDefinition.Option2 = option2;
            questionDefinition.Option3 = option3;
            questionDefinition.Option4 = option4;
            questionDefinition.Option5 = option5;
            questionDefinition.Option6 = option6;
            questionDefinition.CorrectAns = correctAns;
            questionDefinition.Explanation = explanation;
            return questionDefinition;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionData
        {
            get
            {
                return _QuestionData;
            }
            set
            {
                OnQuestionDataChanging(value);
                ReportPropertyChanging("QuestionData");
                _QuestionData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QuestionData");
                OnQuestionDataChanged();
            }
        }
        private global::System.String _QuestionData;
        partial void OnQuestionDataChanging(global::System.String value);
        partial void OnQuestionDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionTypeName
        {
            get
            {
                return _QuestionTypeName;
            }
            set
            {
                OnQuestionTypeNameChanging(value);
                ReportPropertyChanging("QuestionTypeName");
                _QuestionTypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QuestionTypeName");
                OnQuestionTypeNameChanged();
            }
        }
        private global::System.String _QuestionTypeName;
        partial void OnQuestionTypeNameChanging(global::System.String value);
        partial void OnQuestionTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private global::System.Int32 _SortOrder;
        partial void OnSortOrderChanging(global::System.Int32 value);
        partial void OnSortOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuizDefinitionKey
        {
            get
            {
                return _QuizDefinitionKey;
            }
            set
            {
                OnQuizDefinitionKeyChanging(value);
                ReportPropertyChanging("QuizDefinitionKey");
                _QuizDefinitionKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuizDefinitionKey");
                OnQuizDefinitionKeyChanged();
            }
        }
        private global::System.Int32 _QuizDefinitionKey;
        partial void OnQuizDefinitionKeyChanging(global::System.Int32 value);
        partial void OnQuizDefinitionKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QuestionText
        {
            get
            {
                return _QuestionText;
            }
            set
            {
                OnQuestionTextChanging(value);
                ReportPropertyChanging("QuestionText");
                _QuestionText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QuestionText");
                OnQuestionTextChanged();
            }
        }
        private global::System.String _QuestionText;
        partial void OnQuestionTextChanging(global::System.String value);
        partial void OnQuestionTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option1
        {
            get
            {
                return _Option1;
            }
            set
            {
                OnOption1Changing(value);
                ReportPropertyChanging("Option1");
                _Option1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Option1");
                OnOption1Changed();
            }
        }
        private global::System.String _Option1;
        partial void OnOption1Changing(global::System.String value);
        partial void OnOption1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option2
        {
            get
            {
                return _Option2;
            }
            set
            {
                OnOption2Changing(value);
                ReportPropertyChanging("Option2");
                _Option2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Option2");
                OnOption2Changed();
            }
        }
        private global::System.String _Option2;
        partial void OnOption2Changing(global::System.String value);
        partial void OnOption2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option3
        {
            get
            {
                return _Option3;
            }
            set
            {
                OnOption3Changing(value);
                ReportPropertyChanging("Option3");
                _Option3 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Option3");
                OnOption3Changed();
            }
        }
        private global::System.String _Option3;
        partial void OnOption3Changing(global::System.String value);
        partial void OnOption3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option4
        {
            get
            {
                return _Option4;
            }
            set
            {
                OnOption4Changing(value);
                ReportPropertyChanging("Option4");
                _Option4 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Option4");
                OnOption4Changed();
            }
        }
        private global::System.String _Option4;
        partial void OnOption4Changing(global::System.String value);
        partial void OnOption4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option5
        {
            get
            {
                return _Option5;
            }
            set
            {
                OnOption5Changing(value);
                ReportPropertyChanging("Option5");
                _Option5 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Option5");
                OnOption5Changed();
            }
        }
        private global::System.String _Option5;
        partial void OnOption5Changing(global::System.String value);
        partial void OnOption5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option6
        {
            get
            {
                return _Option6;
            }
            set
            {
                OnOption6Changing(value);
                ReportPropertyChanging("Option6");
                _Option6 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Option6");
                OnOption6Changed();
            }
        }
        private global::System.String _Option6;
        partial void OnOption6Changing(global::System.String value);
        partial void OnOption6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CorrectAns
        {
            get
            {
                return _CorrectAns;
            }
            set
            {
                OnCorrectAnsChanging(value);
                ReportPropertyChanging("CorrectAns");
                _CorrectAns = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CorrectAns");
                OnCorrectAnsChanged();
            }
        }
        private global::System.Int32 _CorrectAns;
        partial void OnCorrectAnsChanging(global::System.Int32 value);
        partial void OnCorrectAnsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Explanation
        {
            get
            {
                return _Explanation;
            }
            set
            {
                OnExplanationChanging(value);
                ReportPropertyChanging("Explanation");
                _Explanation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Explanation");
                OnExplanationChanged();
            }
        }
        private global::System.String _Explanation;
        partial void OnExplanationChanging(global::System.String value);
        partial void OnExplanationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuizDbModel", "FK_QuestionDefinitions_Quiz_GiveAQuizModel_QuizDefinitions1", "QuizDefinitions")]
        public QuizDefinition QuizDefinition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuizDefinition>("QuizDbModel.FK_QuestionDefinitions_Quiz_GiveAQuizModel_QuizDefinitions1", "QuizDefinitions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuizDefinition>("QuizDbModel.FK_QuestionDefinitions_Quiz_GiveAQuizModel_QuizDefinitions1", "QuizDefinitions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QuizDefinition> QuizDefinitionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuizDefinition>("QuizDbModel.FK_QuestionDefinitions_Quiz_GiveAQuizModel_QuizDefinitions1", "QuizDefinitions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QuizDefinition>("QuizDbModel.FK_QuestionDefinitions_Quiz_GiveAQuizModel_QuizDefinitions1", "QuizDefinitions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuizDbModel", "FK_QuizAnswers_QuestionDefinitions", "QuizAnswers")]
        public EntityCollection<QuizAnswer> QuizAnswers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<QuizAnswer>("QuizDbModel.FK_QuizAnswers_QuestionDefinitions", "QuizAnswers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<QuizAnswer>("QuizDbModel.FK_QuizAnswers_QuestionDefinitions", "QuizAnswers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuizDbModel", Name="QuizAnswer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuizAnswer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuizAnswer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="questionDefinitionKey">Initial value of the QuestionDefinitionKey property.</param>
        /// <param name="result">Initial value of the Result property.</param>
        /// <param name="answerText">Initial value of the AnswerText property.</param>
        /// <param name="correctAnswerText">Initial value of the CorrectAnswerText property.</param>
        public static QuizAnswer CreateQuizAnswer(global::System.Int32 id, global::System.Int32 questionDefinitionKey, global::System.String result, global::System.String answerText, global::System.String correctAnswerText)
        {
            QuizAnswer quizAnswer = new QuizAnswer();
            quizAnswer.Id = id;
            quizAnswer.QuestionDefinitionKey = questionDefinitionKey;
            quizAnswer.Result = result;
            quizAnswer.AnswerText = answerText;
            quizAnswer.CorrectAnswerText = correctAnswerText;
            return quizAnswer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QuizzKey
        {
            get
            {
                return _QuizzKey;
            }
            set
            {
                OnQuizzKeyChanging(value);
                ReportPropertyChanging("QuizzKey");
                _QuizzKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuizzKey");
                OnQuizzKeyChanged();
            }
        }
        private Nullable<global::System.Int32> _QuizzKey;
        partial void OnQuizzKeyChanging(Nullable<global::System.Int32> value);
        partial void OnQuizzKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionDefinitionKey
        {
            get
            {
                return _QuestionDefinitionKey;
            }
            set
            {
                OnQuestionDefinitionKeyChanging(value);
                ReportPropertyChanging("QuestionDefinitionKey");
                _QuestionDefinitionKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuestionDefinitionKey");
                OnQuestionDefinitionKeyChanged();
            }
        }
        private global::System.Int32 _QuestionDefinitionKey;
        partial void OnQuestionDefinitionKeyChanging(global::System.Int32 value);
        partial void OnQuestionDefinitionKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Result
        {
            get
            {
                return _Result;
            }
            set
            {
                OnResultChanging(value);
                ReportPropertyChanging("Result");
                _Result = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Result");
                OnResultChanged();
            }
        }
        private global::System.String _Result;
        partial void OnResultChanging(global::System.String value);
        partial void OnResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AnswerText
        {
            get
            {
                return _AnswerText;
            }
            set
            {
                OnAnswerTextChanging(value);
                ReportPropertyChanging("AnswerText");
                _AnswerText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AnswerText");
                OnAnswerTextChanged();
            }
        }
        private global::System.String _AnswerText;
        partial void OnAnswerTextChanging(global::System.String value);
        partial void OnAnswerTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CorrectAnswerText
        {
            get
            {
                return _CorrectAnswerText;
            }
            set
            {
                OnCorrectAnswerTextChanging(value);
                ReportPropertyChanging("CorrectAnswerText");
                _CorrectAnswerText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CorrectAnswerText");
                OnCorrectAnswerTextChanged();
            }
        }
        private global::System.String _CorrectAnswerText;
        partial void OnCorrectAnswerTextChanging(global::System.String value);
        partial void OnCorrectAnswerTextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuizDbModel", "FK_QuizAnswers_QuestionDefinitions", "QuestionDefinitions")]
        public QuestionDefinition QuestionDefinition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuestionDefinition>("QuizDbModel.FK_QuizAnswers_QuestionDefinitions", "QuestionDefinitions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuestionDefinition>("QuizDbModel.FK_QuizAnswers_QuestionDefinitions", "QuestionDefinitions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QuestionDefinition> QuestionDefinitionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuestionDefinition>("QuizDbModel.FK_QuizAnswers_QuestionDefinitions", "QuestionDefinitions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QuestionDefinition>("QuizDbModel.FK_QuizAnswers_QuestionDefinitions", "QuestionDefinitions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuizDbModel", "FK_QuizAnswers_Quizzes", "Quizzes")]
        public Quizze Quizze
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Quizze>("QuizDbModel.FK_QuizAnswers_Quizzes", "Quizzes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Quizze>("QuizDbModel.FK_QuizAnswers_Quizzes", "Quizzes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Quizze> QuizzeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Quizze>("QuizDbModel.FK_QuizAnswers_Quizzes", "Quizzes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Quizze>("QuizDbModel.FK_QuizAnswers_Quizzes", "Quizzes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuizDbModel", Name="QuizDefinition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuizDefinition : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuizDefinition object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="quizName">Initial value of the QuizName property.</param>
        /// <param name="owner">Initial value of the Owner property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="timeLimitInMinutes">Initial value of the TimeLimitInMinutes property.</param>
        public static QuizDefinition CreateQuizDefinition(global::System.Int32 id, global::System.String quizName, global::System.Guid owner, global::System.String description, global::System.Int32 timeLimitInMinutes)
        {
            QuizDefinition quizDefinition = new QuizDefinition();
            quizDefinition.Id = id;
            quizDefinition.QuizName = quizName;
            quizDefinition.Owner = owner;
            quizDefinition.Description = description;
            quizDefinition.TimeLimitInMinutes = timeLimitInMinutes;
            return quizDefinition;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuizName
        {
            get
            {
                return _QuizName;
            }
            set
            {
                OnQuizNameChanging(value);
                ReportPropertyChanging("QuizName");
                _QuizName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QuizName");
                OnQuizNameChanged();
            }
        }
        private global::System.String _QuizName;
        partial void OnQuizNameChanging(global::System.String value);
        partial void OnQuizNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                OnOwnerChanging(value);
                ReportPropertyChanging("Owner");
                _Owner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Owner");
                OnOwnerChanged();
            }
        }
        private global::System.Guid _Owner;
        partial void OnOwnerChanging(global::System.Guid value);
        partial void OnOwnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeLimitInMinutes
        {
            get
            {
                return _TimeLimitInMinutes;
            }
            set
            {
                OnTimeLimitInMinutesChanging(value);
                ReportPropertyChanging("TimeLimitInMinutes");
                _TimeLimitInMinutes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeLimitInMinutes");
                OnTimeLimitInMinutesChanged();
            }
        }
        private global::System.Int32 _TimeLimitInMinutes;
        partial void OnTimeLimitInMinutesChanging(global::System.Int32 value);
        partial void OnTimeLimitInMinutesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedDate;
        partial void OnUpdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuizDbModel", "FK_QuestionDefinitions_Quiz_GiveAQuizModel_QuizDefinitions1", "QuestionDefinitions")]
        public EntityCollection<QuestionDefinition> QuestionDefinitions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<QuestionDefinition>("QuizDbModel.FK_QuestionDefinitions_Quiz_GiveAQuizModel_QuizDefinitions1", "QuestionDefinitions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<QuestionDefinition>("QuizDbModel.FK_QuestionDefinitions_Quiz_GiveAQuizModel_QuizDefinitions1", "QuestionDefinitions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuizDbModel", "FK_Quizzes_QuizDefinition_GiveAQuizModel_QuizDefinitions", "Quizzes")]
        public EntityCollection<Quizze> Quizzes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Quizze>("QuizDbModel.FK_Quizzes_QuizDefinition_GiveAQuizModel_QuizDefinitions", "Quizzes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Quizze>("QuizDbModel.FK_Quizzes_QuizDefinition_GiveAQuizModel_QuizDefinitions", "Quizzes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuizDbModel", Name="Quizze")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Quizze : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Quizze object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="isNameOptional">Initial value of the IsNameOptional property.</param>
        /// <param name="hasEnded">Initial value of the HasEnded property.</param>
        /// <param name="quizDefinitionID">Initial value of the QuizDefinitionID property.</param>
        public static Quizze CreateQuizze(global::System.Int32 id, global::System.String name, global::System.DateTime startDate, global::System.DateTime endDate, global::System.Boolean isNameOptional, global::System.Boolean hasEnded, global::System.Int32 quizDefinitionID)
        {
            Quizze quizze = new Quizze();
            quizze.Id = id;
            quizze.Name = name;
            quizze.StartDate = startDate;
            quizze.EndDate = endDate;
            quizze.IsNameOptional = isNameOptional;
            quizze.HasEnded = hasEnded;
            quizze.QuizDefinitionID = quizDefinitionID;
            return quizze;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNameOptional
        {
            get
            {
                return _IsNameOptional;
            }
            set
            {
                OnIsNameOptionalChanging(value);
                ReportPropertyChanging("IsNameOptional");
                _IsNameOptional = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNameOptional");
                OnIsNameOptionalChanged();
            }
        }
        private global::System.Boolean _IsNameOptional;
        partial void OnIsNameOptionalChanging(global::System.Boolean value);
        partial void OnIsNameOptionalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasEnded
        {
            get
            {
                return _HasEnded;
            }
            set
            {
                OnHasEndedChanging(value);
                ReportPropertyChanging("HasEnded");
                _HasEnded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasEnded");
                OnHasEndedChanged();
            }
        }
        private global::System.Boolean _HasEnded;
        partial void OnHasEndedChanging(global::System.Boolean value);
        partial void OnHasEndedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuizDefinitionID
        {
            get
            {
                return _QuizDefinitionID;
            }
            set
            {
                OnQuizDefinitionIDChanging(value);
                ReportPropertyChanging("QuizDefinitionID");
                _QuizDefinitionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuizDefinitionID");
                OnQuizDefinitionIDChanged();
            }
        }
        private global::System.Int32 _QuizDefinitionID;
        partial void OnQuizDefinitionIDChanging(global::System.Int32 value);
        partial void OnQuizDefinitionIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuizDbModel", "FK_QuizAnswers_Quizzes", "QuizAnswers")]
        public EntityCollection<QuizAnswer> QuizAnswers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<QuizAnswer>("QuizDbModel.FK_QuizAnswers_Quizzes", "QuizAnswers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<QuizAnswer>("QuizDbModel.FK_QuizAnswers_Quizzes", "QuizAnswers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuizDbModel", "FK_Quizzes_QuizDefinition_GiveAQuizModel_QuizDefinitions", "QuizDefinitions")]
        public QuizDefinition QuizDefinition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuizDefinition>("QuizDbModel.FK_Quizzes_QuizDefinition_GiveAQuizModel_QuizDefinitions", "QuizDefinitions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuizDefinition>("QuizDbModel.FK_Quizzes_QuizDefinition_GiveAQuizModel_QuizDefinitions", "QuizDefinitions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QuizDefinition> QuizDefinitionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuizDefinition>("QuizDbModel.FK_Quizzes_QuizDefinition_GiveAQuizModel_QuizDefinitions", "QuizDefinitions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QuizDefinition>("QuizDbModel.FK_Quizzes_QuizDefinition_GiveAQuizModel_QuizDefinitions", "QuizDefinitions", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuizDbModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
