// SharePointCollector.idl : IDL source for SharePointCollector
//

// This file will be processed by the MIDL tool to
// produce the type library (SharePointCollector.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "inboundCollector.idl"

[
	object,
	uuid(7A40C4C5-77F1-4350-A59D-854CEAA22F32),
	dual,
	nonextensible,
	helpstring("ISharePointCollect Interface"),
	pointer_default(unique)
]
interface ISharePointCollect : IDispatch{
};
[
	uuid(37F2B5D2-AD4B-41D9-B5F5-E72794D7DA0F),
	version(1.0),
	helpstring("SharePointCollector 1.0 Type Library")
]
library SharePointCollectorLib
{
	importlib("stdole2.tlb");
	[
		uuid(16B172C2-8025-4E85-A636-90EF654A115A),
		helpstring("SharePointCollect Class")
	]
	coclass SharePointCollect
	{
		[default] interface ISharePointCollect;
	};
};
