//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduEnginee.Areas.Visa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContinentSet
    {
        public ContinentSet()
        {
            this.CountrySet = new HashSet<CountrySet>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<CountrySet> CountrySet { get; set; }
    }
}
