//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduEnginee.Areas.Visa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountrySet
    {
        public CountrySet()
        {
            this.ForeignStudySet = new HashSet<ForeignStudySet>();
            this.VisaProcedureSet = new HashSet<VisaProcedureSet>();
            this.CouncellingFirmSet = new HashSet<CouncellingFirmSet>();
        }
    
        public int Id { get; set; }
        public int ContinentId { get; set; }
        public string Title { get; set; }
    
        public virtual ContinentSet ContinentSet { get; set; }
        public virtual ICollection<ForeignStudySet> ForeignStudySet { get; set; }
        public virtual ICollection<VisaProcedureSet> VisaProcedureSet { get; set; }
        public virtual ICollection<CouncellingFirmSet> CouncellingFirmSet { get; set; }
    }
}
