//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduEnginee.Areas.Visa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaTypeSet
    {
        public VisaTypeSet()
        {
            this.VisaProcedureSet = new HashSet<VisaProcedureSet>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<VisaProcedureSet> VisaProcedureSet { get; set; }
    }
}
