//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduEnginee.Areas.Visa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class VisaProcedureSet
    {
        public int Id { get; set; }
        public string Visafee { get; set; }
        public string VFS_charge { get; set; }
        [DataType(DataType.MultilineText)]
        public string RequiredDocument { get; set; }
        [DataType(DataType.MultilineText)]
        public string Where_toApply { get; set; }
        [DataType(DataType.MultilineText)]
        public string SpecialNote { get; set; }
        [DataType(DataType.MultilineText)]
        public string PhotographyInformation { get; set; }
        [DataType(DataType.MultilineText)]
        public string BasicRequirement { get; set; }
        public int VisaTypeId { get; set; }
        public int Country_Id { get; set; }
    
        public virtual CountrySet CountrySet { get; set; }
        public virtual VisaTypeSet VisaTypeSet { get; set; }
    }
}
