//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StudyAbroadModel", "FK_ContinentCountry", "ContinentSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduEnginee.Areas.StudyAbroad.Models.ContinentSet), "CountrySet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Areas.StudyAbroad.Models.CountrySet), true)]
[assembly: EdmRelationshipAttribute("StudyAbroadModel", "FK_CountryForeignStudy", "CountrySet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduEnginee.Areas.StudyAbroad.Models.CountrySet), "ForeignStudySet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Areas.StudyAbroad.Models.ForeignStudySet), true)]
[assembly: EdmRelationshipAttribute("StudyAbroadModel", "FK_CountryVisaProcedure", "CountrySet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduEnginee.Areas.StudyAbroad.Models.CountrySet), "VisaProcedureSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Areas.StudyAbroad.Models.VisaProcedureSet), true)]
[assembly: EdmRelationshipAttribute("StudyAbroadModel", "FK_VisaTypeVisaProcedure", "VisaTypeSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduEnginee.Areas.StudyAbroad.Models.VisaTypeSet), "VisaProcedureSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Areas.StudyAbroad.Models.VisaProcedureSet), true)]
[assembly: EdmRelationshipAttribute("StudyAbroadModel", "CountryCouncellingFirm", "CouncellingFirmSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Areas.StudyAbroad.Models.CouncellingFirmSet), "CountrySet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduEnginee.Areas.StudyAbroad.Models.CountrySet))]

#endregion

namespace EduEnginee.Areas.StudyAbroad.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StudyAbroadEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StudyAbroadEntities object using the connection string found in the 'StudyAbroadEntities' section of the application configuration file.
        /// </summary>
        public StudyAbroadEntities() : base("name=StudyAbroadEntities", "StudyAbroadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudyAbroadEntities object.
        /// </summary>
        public StudyAbroadEntities(string connectionString) : base(connectionString, "StudyAbroadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudyAbroadEntities object.
        /// </summary>
        public StudyAbroadEntities(EntityConnection connection) : base(connection, "StudyAbroadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContinentSet> ContinentSet
        {
            get
            {
                if ((_ContinentSet == null))
                {
                    _ContinentSet = base.CreateObjectSet<ContinentSet>("ContinentSet");
                }
                return _ContinentSet;
            }
        }
        private ObjectSet<ContinentSet> _ContinentSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CouncellingFirmSet> CouncellingFirmSet
        {
            get
            {
                if ((_CouncellingFirmSet == null))
                {
                    _CouncellingFirmSet = base.CreateObjectSet<CouncellingFirmSet>("CouncellingFirmSet");
                }
                return _CouncellingFirmSet;
            }
        }
        private ObjectSet<CouncellingFirmSet> _CouncellingFirmSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CountrySet> CountrySet
        {
            get
            {
                if ((_CountrySet == null))
                {
                    _CountrySet = base.CreateObjectSet<CountrySet>("CountrySet");
                }
                return _CountrySet;
            }
        }
        private ObjectSet<CountrySet> _CountrySet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ForeignStudySet> ForeignStudySet
        {
            get
            {
                if ((_ForeignStudySet == null))
                {
                    _ForeignStudySet = base.CreateObjectSet<ForeignStudySet>("ForeignStudySet");
                }
                return _ForeignStudySet;
            }
        }
        private ObjectSet<ForeignStudySet> _ForeignStudySet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VisaProcedureSet> VisaProcedureSet
        {
            get
            {
                if ((_VisaProcedureSet == null))
                {
                    _VisaProcedureSet = base.CreateObjectSet<VisaProcedureSet>("VisaProcedureSet");
                }
                return _VisaProcedureSet;
            }
        }
        private ObjectSet<VisaProcedureSet> _VisaProcedureSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VisaTypeSet> VisaTypeSet
        {
            get
            {
                if ((_VisaTypeSet == null))
                {
                    _VisaTypeSet = base.CreateObjectSet<VisaTypeSet>("VisaTypeSet");
                }
                return _VisaTypeSet;
            }
        }
        private ObjectSet<VisaTypeSet> _VisaTypeSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContinentSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContinentSet(ContinentSet continentSet)
        {
            base.AddObject("ContinentSet", continentSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CouncellingFirmSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCouncellingFirmSet(CouncellingFirmSet councellingFirmSet)
        {
            base.AddObject("CouncellingFirmSet", councellingFirmSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CountrySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCountrySet(CountrySet countrySet)
        {
            base.AddObject("CountrySet", countrySet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ForeignStudySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToForeignStudySet(ForeignStudySet foreignStudySet)
        {
            base.AddObject("ForeignStudySet", foreignStudySet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VisaProcedureSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVisaProcedureSet(VisaProcedureSet visaProcedureSet)
        {
            base.AddObject("VisaProcedureSet", visaProcedureSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VisaTypeSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVisaTypeSet(VisaTypeSet visaTypeSet)
        {
            base.AddObject("VisaTypeSet", visaTypeSet);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudyAbroadModel", Name="ContinentSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContinentSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContinentSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static ContinentSet CreateContinentSet(global::System.Int32 id, global::System.String title)
        {
            ContinentSet continentSet = new ContinentSet();
            continentSet.Id = id;
            continentSet.Title = title;
            return continentSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "FK_ContinentCountry", "CountrySet")]
        public EntityCollection<CountrySet> CountrySet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CountrySet>("StudyAbroadModel.FK_ContinentCountry", "CountrySet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CountrySet>("StudyAbroadModel.FK_ContinentCountry", "CountrySet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudyAbroadModel", Name="CouncellingFirmSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CouncellingFirmSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CouncellingFirmSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="mobile">Initial value of the Mobile property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="fax">Initial value of the Fax property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="web">Initial value of the Web property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="directorName">Initial value of the DirectorName property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static CouncellingFirmSet CreateCouncellingFirmSet(global::System.Int32 id, global::System.String mobile, global::System.String phone, global::System.String fax, global::System.String email, global::System.String web, global::System.String description, global::System.String directorName, global::System.String address)
        {
            CouncellingFirmSet councellingFirmSet = new CouncellingFirmSet();
            councellingFirmSet.Id = id;
            councellingFirmSet.Mobile = mobile;
            councellingFirmSet.Phone = phone;
            councellingFirmSet.Fax = fax;
            councellingFirmSet.Email = email;
            councellingFirmSet.Web = web;
            councellingFirmSet.Description = description;
            councellingFirmSet.DirectorName = directorName;
            councellingFirmSet.Address = address;
            return councellingFirmSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Web
        {
            get
            {
                return _Web;
            }
            set
            {
                OnWebChanging(value);
                ReportPropertyChanging("Web");
                _Web = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Web");
                OnWebChanged();
            }
        }
        private global::System.String _Web;
        partial void OnWebChanging(global::System.String value);
        partial void OnWebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DirectorName
        {
            get
            {
                return _DirectorName;
            }
            set
            {
                OnDirectorNameChanging(value);
                ReportPropertyChanging("DirectorName");
                _DirectorName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DirectorName");
                OnDirectorNameChanged();
            }
        }
        private global::System.String _DirectorName;
        partial void OnDirectorNameChanging(global::System.String value);
        partial void OnDirectorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "CountryCouncellingFirm", "CountrySet")]
        public EntityCollection<CountrySet> CountrySet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CountrySet>("StudyAbroadModel.CountryCouncellingFirm", "CountrySet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CountrySet>("StudyAbroadModel.CountryCouncellingFirm", "CountrySet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudyAbroadModel", Name="CountrySet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CountrySet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CountrySet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="continentId">Initial value of the ContinentId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static CountrySet CreateCountrySet(global::System.Int32 id, global::System.Int32 continentId, global::System.String title)
        {
            CountrySet countrySet = new CountrySet();
            countrySet.Id = id;
            countrySet.ContinentId = continentId;
            countrySet.Title = title;
            return countrySet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContinentId
        {
            get
            {
                return _ContinentId;
            }
            set
            {
                OnContinentIdChanging(value);
                ReportPropertyChanging("ContinentId");
                _ContinentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContinentId");
                OnContinentIdChanged();
            }
        }
        private global::System.Int32 _ContinentId;
        partial void OnContinentIdChanging(global::System.Int32 value);
        partial void OnContinentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "FK_ContinentCountry", "ContinentSet")]
        public ContinentSet ContinentSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContinentSet>("StudyAbroadModel.FK_ContinentCountry", "ContinentSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContinentSet>("StudyAbroadModel.FK_ContinentCountry", "ContinentSet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ContinentSet> ContinentSetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContinentSet>("StudyAbroadModel.FK_ContinentCountry", "ContinentSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ContinentSet>("StudyAbroadModel.FK_ContinentCountry", "ContinentSet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "FK_CountryForeignStudy", "ForeignStudySet")]
        public EntityCollection<ForeignStudySet> ForeignStudySet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ForeignStudySet>("StudyAbroadModel.FK_CountryForeignStudy", "ForeignStudySet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ForeignStudySet>("StudyAbroadModel.FK_CountryForeignStudy", "ForeignStudySet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "FK_CountryVisaProcedure", "VisaProcedureSet")]
        public EntityCollection<VisaProcedureSet> VisaProcedureSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VisaProcedureSet>("StudyAbroadModel.FK_CountryVisaProcedure", "VisaProcedureSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VisaProcedureSet>("StudyAbroadModel.FK_CountryVisaProcedure", "VisaProcedureSet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "CountryCouncellingFirm", "CouncellingFirmSet")]
        public EntityCollection<CouncellingFirmSet> CouncellingFirmSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CouncellingFirmSet>("StudyAbroadModel.CountryCouncellingFirm", "CouncellingFirmSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CouncellingFirmSet>("StudyAbroadModel.CountryCouncellingFirm", "CouncellingFirmSet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudyAbroadModel", Name="ForeignStudySet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ForeignStudySet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ForeignStudySet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="visaTypeId">Initial value of the VisaTypeId property.</param>
        /// <param name="countryId">Initial value of the CountryId property.</param>
        /// <param name="degrees">Initial value of the Degrees property.</param>
        /// <param name="semesterOffer">Initial value of the SemesterOffer property.</param>
        /// <param name="requirementsForBachelorsProgram">Initial value of the RequirementsForBachelorsProgram property.</param>
        /// <param name="requirementsForMastersProgram">Initial value of the RequirementsForMastersProgram property.</param>
        /// <param name="subjects">Initial value of the Subjects property.</param>
        /// <param name="expenses">Initial value of the Expenses property.</param>
        /// <param name="applyProcedure">Initial value of the ApplyProcedure property.</param>
        /// <param name="supportingDocuments">Initial value of the SupportingDocuments property.</param>
        /// <param name="creditTransfer">Initial value of the CreditTransfer property.</param>
        /// <param name="otherInformation">Initial value of the OtherInformation property.</param>
        /// <param name="country_Id">Initial value of the Country_Id property.</param>
        public static ForeignStudySet CreateForeignStudySet(global::System.Int32 id, global::System.Int32 visaTypeId, global::System.Int32 countryId, global::System.String degrees, global::System.String semesterOffer, global::System.String requirementsForBachelorsProgram, global::System.String requirementsForMastersProgram, global::System.String subjects, global::System.String expenses, global::System.String applyProcedure, global::System.String supportingDocuments, global::System.String creditTransfer, global::System.String otherInformation, global::System.Int32 country_Id)
        {
            ForeignStudySet foreignStudySet = new ForeignStudySet();
            foreignStudySet.Id = id;
            foreignStudySet.VisaTypeId = visaTypeId;
            foreignStudySet.CountryId = countryId;
            foreignStudySet.Degrees = degrees;
            foreignStudySet.SemesterOffer = semesterOffer;
            foreignStudySet.RequirementsForBachelorsProgram = requirementsForBachelorsProgram;
            foreignStudySet.RequirementsForMastersProgram = requirementsForMastersProgram;
            foreignStudySet.Subjects = subjects;
            foreignStudySet.Expenses = expenses;
            foreignStudySet.ApplyProcedure = applyProcedure;
            foreignStudySet.SupportingDocuments = supportingDocuments;
            foreignStudySet.CreditTransfer = creditTransfer;
            foreignStudySet.OtherInformation = otherInformation;
            foreignStudySet.Country_Id = country_Id;
            return foreignStudySet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VisaTypeId
        {
            get
            {
                return _VisaTypeId;
            }
            set
            {
                OnVisaTypeIdChanging(value);
                ReportPropertyChanging("VisaTypeId");
                _VisaTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisaTypeId");
                OnVisaTypeIdChanged();
            }
        }
        private global::System.Int32 _VisaTypeId;
        partial void OnVisaTypeIdChanging(global::System.Int32 value);
        partial void OnVisaTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CountryId
        {
            get
            {
                return _CountryId;
            }
            set
            {
                OnCountryIdChanging(value);
                ReportPropertyChanging("CountryId");
                _CountryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountryId");
                OnCountryIdChanged();
            }
        }
        private global::System.Int32 _CountryId;
        partial void OnCountryIdChanging(global::System.Int32 value);
        partial void OnCountryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Degrees
        {
            get
            {
                return _Degrees;
            }
            set
            {
                OnDegreesChanging(value);
                ReportPropertyChanging("Degrees");
                _Degrees = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Degrees");
                OnDegreesChanged();
            }
        }
        private global::System.String _Degrees;
        partial void OnDegreesChanging(global::System.String value);
        partial void OnDegreesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SemesterOffer
        {
            get
            {
                return _SemesterOffer;
            }
            set
            {
                OnSemesterOfferChanging(value);
                ReportPropertyChanging("SemesterOffer");
                _SemesterOffer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SemesterOffer");
                OnSemesterOfferChanged();
            }
        }
        private global::System.String _SemesterOffer;
        partial void OnSemesterOfferChanging(global::System.String value);
        partial void OnSemesterOfferChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequirementsForBachelorsProgram
        {
            get
            {
                return _RequirementsForBachelorsProgram;
            }
            set
            {
                OnRequirementsForBachelorsProgramChanging(value);
                ReportPropertyChanging("RequirementsForBachelorsProgram");
                _RequirementsForBachelorsProgram = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequirementsForBachelorsProgram");
                OnRequirementsForBachelorsProgramChanged();
            }
        }
        private global::System.String _RequirementsForBachelorsProgram;
        partial void OnRequirementsForBachelorsProgramChanging(global::System.String value);
        partial void OnRequirementsForBachelorsProgramChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequirementsForMastersProgram
        {
            get
            {
                return _RequirementsForMastersProgram;
            }
            set
            {
                OnRequirementsForMastersProgramChanging(value);
                ReportPropertyChanging("RequirementsForMastersProgram");
                _RequirementsForMastersProgram = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequirementsForMastersProgram");
                OnRequirementsForMastersProgramChanged();
            }
        }
        private global::System.String _RequirementsForMastersProgram;
        partial void OnRequirementsForMastersProgramChanging(global::System.String value);
        partial void OnRequirementsForMastersProgramChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subjects
        {
            get
            {
                return _Subjects;
            }
            set
            {
                OnSubjectsChanging(value);
                ReportPropertyChanging("Subjects");
                _Subjects = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subjects");
                OnSubjectsChanged();
            }
        }
        private global::System.String _Subjects;
        partial void OnSubjectsChanging(global::System.String value);
        partial void OnSubjectsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Expenses
        {
            get
            {
                return _Expenses;
            }
            set
            {
                OnExpensesChanging(value);
                ReportPropertyChanging("Expenses");
                _Expenses = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Expenses");
                OnExpensesChanged();
            }
        }
        private global::System.String _Expenses;
        partial void OnExpensesChanging(global::System.String value);
        partial void OnExpensesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplyProcedure
        {
            get
            {
                return _ApplyProcedure;
            }
            set
            {
                OnApplyProcedureChanging(value);
                ReportPropertyChanging("ApplyProcedure");
                _ApplyProcedure = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApplyProcedure");
                OnApplyProcedureChanged();
            }
        }
        private global::System.String _ApplyProcedure;
        partial void OnApplyProcedureChanging(global::System.String value);
        partial void OnApplyProcedureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SupportingDocuments
        {
            get
            {
                return _SupportingDocuments;
            }
            set
            {
                OnSupportingDocumentsChanging(value);
                ReportPropertyChanging("SupportingDocuments");
                _SupportingDocuments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SupportingDocuments");
                OnSupportingDocumentsChanged();
            }
        }
        private global::System.String _SupportingDocuments;
        partial void OnSupportingDocumentsChanging(global::System.String value);
        partial void OnSupportingDocumentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreditTransfer
        {
            get
            {
                return _CreditTransfer;
            }
            set
            {
                OnCreditTransferChanging(value);
                ReportPropertyChanging("CreditTransfer");
                _CreditTransfer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreditTransfer");
                OnCreditTransferChanged();
            }
        }
        private global::System.String _CreditTransfer;
        partial void OnCreditTransferChanging(global::System.String value);
        partial void OnCreditTransferChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OtherInformation
        {
            get
            {
                return _OtherInformation;
            }
            set
            {
                OnOtherInformationChanging(value);
                ReportPropertyChanging("OtherInformation");
                _OtherInformation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OtherInformation");
                OnOtherInformationChanged();
            }
        }
        private global::System.String _OtherInformation;
        partial void OnOtherInformationChanging(global::System.String value);
        partial void OnOtherInformationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Country_Id
        {
            get
            {
                return _Country_Id;
            }
            set
            {
                OnCountry_IdChanging(value);
                ReportPropertyChanging("Country_Id");
                _Country_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Country_Id");
                OnCountry_IdChanged();
            }
        }
        private global::System.Int32 _Country_Id;
        partial void OnCountry_IdChanging(global::System.Int32 value);
        partial void OnCountry_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "FK_CountryForeignStudy", "CountrySet")]
        public CountrySet CountrySet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CountrySet>("StudyAbroadModel.FK_CountryForeignStudy", "CountrySet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CountrySet>("StudyAbroadModel.FK_CountryForeignStudy", "CountrySet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CountrySet> CountrySetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CountrySet>("StudyAbroadModel.FK_CountryForeignStudy", "CountrySet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CountrySet>("StudyAbroadModel.FK_CountryForeignStudy", "CountrySet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudyAbroadModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudyAbroadModel", Name="VisaProcedureSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VisaProcedureSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VisaProcedureSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="visafee">Initial value of the Visafee property.</param>
        /// <param name="requiredDocument">Initial value of the RequiredDocument property.</param>
        /// <param name="where_toApply">Initial value of the Where_toApply property.</param>
        /// <param name="specialNote">Initial value of the SpecialNote property.</param>
        /// <param name="photographyInformation">Initial value of the PhotographyInformation property.</param>
        /// <param name="basicRequirement">Initial value of the BasicRequirement property.</param>
        /// <param name="visaTypeId">Initial value of the VisaTypeId property.</param>
        /// <param name="country_Id">Initial value of the Country_Id property.</param>
        public static VisaProcedureSet CreateVisaProcedureSet(global::System.Int32 id, global::System.String visafee, global::System.String requiredDocument, global::System.String where_toApply, global::System.String specialNote, global::System.String photographyInformation, global::System.String basicRequirement, global::System.Int32 visaTypeId, global::System.Int32 country_Id)
        {
            VisaProcedureSet visaProcedureSet = new VisaProcedureSet();
            visaProcedureSet.Id = id;
            visaProcedureSet.Visafee = visafee;
            visaProcedureSet.RequiredDocument = requiredDocument;
            visaProcedureSet.Where_toApply = where_toApply;
            visaProcedureSet.SpecialNote = specialNote;
            visaProcedureSet.PhotographyInformation = photographyInformation;
            visaProcedureSet.BasicRequirement = basicRequirement;
            visaProcedureSet.VisaTypeId = visaTypeId;
            visaProcedureSet.Country_Id = country_Id;
            return visaProcedureSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Visafee
        {
            get
            {
                return _Visafee;
            }
            set
            {
                OnVisafeeChanging(value);
                ReportPropertyChanging("Visafee");
                _Visafee = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Visafee");
                OnVisafeeChanged();
            }
        }
        private global::System.String _Visafee;
        partial void OnVisafeeChanging(global::System.String value);
        partial void OnVisafeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequiredDocument
        {
            get
            {
                return _RequiredDocument;
            }
            set
            {
                OnRequiredDocumentChanging(value);
                ReportPropertyChanging("RequiredDocument");
                _RequiredDocument = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequiredDocument");
                OnRequiredDocumentChanged();
            }
        }
        private global::System.String _RequiredDocument;
        partial void OnRequiredDocumentChanging(global::System.String value);
        partial void OnRequiredDocumentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Where_toApply
        {
            get
            {
                return _Where_toApply;
            }
            set
            {
                OnWhere_toApplyChanging(value);
                ReportPropertyChanging("Where_toApply");
                _Where_toApply = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Where_toApply");
                OnWhere_toApplyChanged();
            }
        }
        private global::System.String _Where_toApply;
        partial void OnWhere_toApplyChanging(global::System.String value);
        partial void OnWhere_toApplyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SpecialNote
        {
            get
            {
                return _SpecialNote;
            }
            set
            {
                OnSpecialNoteChanging(value);
                ReportPropertyChanging("SpecialNote");
                _SpecialNote = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SpecialNote");
                OnSpecialNoteChanged();
            }
        }
        private global::System.String _SpecialNote;
        partial void OnSpecialNoteChanging(global::System.String value);
        partial void OnSpecialNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhotographyInformation
        {
            get
            {
                return _PhotographyInformation;
            }
            set
            {
                OnPhotographyInformationChanging(value);
                ReportPropertyChanging("PhotographyInformation");
                _PhotographyInformation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhotographyInformation");
                OnPhotographyInformationChanged();
            }
        }
        private global::System.String _PhotographyInformation;
        partial void OnPhotographyInformationChanging(global::System.String value);
        partial void OnPhotographyInformationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BasicRequirement
        {
            get
            {
                return _BasicRequirement;
            }
            set
            {
                OnBasicRequirementChanging(value);
                ReportPropertyChanging("BasicRequirement");
                _BasicRequirement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BasicRequirement");
                OnBasicRequirementChanged();
            }
        }
        private global::System.String _BasicRequirement;
        partial void OnBasicRequirementChanging(global::System.String value);
        partial void OnBasicRequirementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VisaTypeId
        {
            get
            {
                return _VisaTypeId;
            }
            set
            {
                OnVisaTypeIdChanging(value);
                ReportPropertyChanging("VisaTypeId");
                _VisaTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisaTypeId");
                OnVisaTypeIdChanged();
            }
        }
        private global::System.Int32 _VisaTypeId;
        partial void OnVisaTypeIdChanging(global::System.Int32 value);
        partial void OnVisaTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Country_Id
        {
            get
            {
                return _Country_Id;
            }
            set
            {
                OnCountry_IdChanging(value);
                ReportPropertyChanging("Country_Id");
                _Country_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Country_Id");
                OnCountry_IdChanged();
            }
        }
        private global::System.Int32 _Country_Id;
        partial void OnCountry_IdChanging(global::System.Int32 value);
        partial void OnCountry_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "FK_CountryVisaProcedure", "CountrySet")]
        public CountrySet CountrySet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CountrySet>("StudyAbroadModel.FK_CountryVisaProcedure", "CountrySet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CountrySet>("StudyAbroadModel.FK_CountryVisaProcedure", "CountrySet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CountrySet> CountrySetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CountrySet>("StudyAbroadModel.FK_CountryVisaProcedure", "CountrySet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CountrySet>("StudyAbroadModel.FK_CountryVisaProcedure", "CountrySet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "FK_VisaTypeVisaProcedure", "VisaTypeSet")]
        public VisaTypeSet VisaTypeSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VisaTypeSet>("StudyAbroadModel.FK_VisaTypeVisaProcedure", "VisaTypeSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VisaTypeSet>("StudyAbroadModel.FK_VisaTypeVisaProcedure", "VisaTypeSet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VisaTypeSet> VisaTypeSetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VisaTypeSet>("StudyAbroadModel.FK_VisaTypeVisaProcedure", "VisaTypeSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VisaTypeSet>("StudyAbroadModel.FK_VisaTypeVisaProcedure", "VisaTypeSet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudyAbroadModel", Name="VisaTypeSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VisaTypeSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VisaTypeSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static VisaTypeSet CreateVisaTypeSet(global::System.Int32 id, global::System.String title)
        {
            VisaTypeSet visaTypeSet = new VisaTypeSet();
            visaTypeSet.Id = id;
            visaTypeSet.Title = title;
            return visaTypeSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StudyAbroadModel", "FK_VisaTypeVisaProcedure", "VisaProcedureSet")]
        public EntityCollection<VisaProcedureSet> VisaProcedureSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VisaProcedureSet>("StudyAbroadModel.FK_VisaTypeVisaProcedure", "VisaProcedureSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VisaProcedureSet>("StudyAbroadModel.FK_VisaTypeVisaProcedure", "VisaProcedureSet", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
