//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EduEnginee.Areas.Admission.Models
{
    public partial class Circular
    {
        public Circular()
        {
            this.Comments = new HashSet<Comment>();
            this.Subjects = new HashSet<Subject>();
        }
    
        public int Id { get; set; }
        public int InstituteId { get; set; }
        public byte[] SeatPlan { get; set; }
        public byte[] Result { get; set; }
        public string ResultLink { get; set; }
        public string SeatPlanLink { get; set; }
        public bool IsEnable { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Session { get; set; }
        public string CourseType { get; set; }
        public string AdmissionReq { get; set; }
        public string ApplyProc { get; set; }
        public Nullable<System.DateTime> AppStart { get; set; }
        public Nullable<System.DateTime> AppEnd { get; set; }
        public Nullable<System.DateTime> SubStart { get; set; }
        public Nullable<System.DateTime> SubEnd { get; set; }
        public Nullable<System.DateTime> EligibleCanDate { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> ResDate { get; set; }
        public int AdmissionTypeId { get; set; }
        public string Title { get; set; }
    
        public virtual AdmissionType AdmissionType { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual Institute Institute { get; set; }
    }
    
}
