//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EduEnginee.Areas.Admission.Models
{
    public partial class Country
    {
        public Country()
        {
            this.Institutes = new HashSet<Institute>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual ICollection<Institute> Institutes { get; set; }
    }
    
}
