//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace EduEnginee.Areas.Admission.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(InstituteSubcatary))]
    [KnownType(typeof(InstituteType))]
    public partial class InstituteCatary: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string Title
        {
            get { return _title; }
            set
            {
                if (_title != value)
                {
                    _title = value;
                    OnPropertyChanged("Title");
                }
            }
        }
        private string _title;
    
        [DataMember]
        public int InstituteTypeId
        {
            get { return _instituteTypeId; }
            set
            {
                if (_instituteTypeId != value)
                {
                    ChangeTracker.RecordOriginalValue("InstituteTypeId", _instituteTypeId);
                    if (!IsDeserializing)
                    {
                        if (InstituteType != null && InstituteType.Id != value)
                        {
                            InstituteType = null;
                        }
                    }
                    _instituteTypeId = value;
                    OnPropertyChanged("InstituteTypeId");
                }
            }
        }
        private int _instituteTypeId;
    
        [DataMember]
        public Nullable<bool> IsEnable
        {
            get { return _isEnable; }
            set
            {
                if (_isEnable != value)
                {
                    _isEnable = value;
                    OnPropertyChanged("IsEnable");
                }
            }
        }
        private Nullable<bool> _isEnable;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<InstituteSubcatary> InstituteSubcataries
        {
            get
            {
                if (_instituteSubcataries == null)
                {
                    _instituteSubcataries = new TrackableCollection<InstituteSubcatary>();
                    _instituteSubcataries.CollectionChanged += FixupInstituteSubcataries;
                }
                return _instituteSubcataries;
            }
            set
            {
                if (!ReferenceEquals(_instituteSubcataries, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_instituteSubcataries != null)
                    {
                        _instituteSubcataries.CollectionChanged -= FixupInstituteSubcataries;
                    }
                    _instituteSubcataries = value;
                    if (_instituteSubcataries != null)
                    {
                        _instituteSubcataries.CollectionChanged += FixupInstituteSubcataries;
                    }
                    OnNavigationPropertyChanged("InstituteSubcataries");
                }
            }
        }
        private TrackableCollection<InstituteSubcatary> _instituteSubcataries;
    
        [DataMember]
        public InstituteType InstituteType
        {
            get { return _instituteType; }
            set
            {
                if (!ReferenceEquals(_instituteType, value))
                {
                    var previousValue = _instituteType;
                    _instituteType = value;
                    FixupInstituteType(previousValue);
                    OnNavigationPropertyChanged("InstituteType");
                }
            }
        }
        private InstituteType _instituteType;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            InstituteSubcataries.Clear();
            InstituteType = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupInstituteType(InstituteType previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.InstituteCataries.Contains(this))
            {
                previousValue.InstituteCataries.Remove(this);
            }
    
            if (InstituteType != null)
            {
                if (!InstituteType.InstituteCataries.Contains(this))
                {
                    InstituteType.InstituteCataries.Add(this);
                }
    
                InstituteTypeId = InstituteType.Id;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("InstituteType")
                    && (ChangeTracker.OriginalValues["InstituteType"] == InstituteType))
                {
                    ChangeTracker.OriginalValues.Remove("InstituteType");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("InstituteType", previousValue);
                }
                if (InstituteType != null && !InstituteType.ChangeTracker.ChangeTrackingEnabled)
                {
                    InstituteType.StartTracking();
                }
            }
        }
    
        private void FixupInstituteSubcataries(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (InstituteSubcatary item in e.NewItems)
                {
                    item.InstituteCatary = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("InstituteSubcataries", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (InstituteSubcatary item in e.OldItems)
                {
                    if (ReferenceEquals(item.InstituteCatary, this))
                    {
                        item.InstituteCatary = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("InstituteSubcataries", item);
                    }
                }
            }
        }

        #endregion

    }
}
