//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace EduEnginee.Areas.Admission.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Circular))]
    public partial class Subject: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string Title
        {
            get { return _title; }
            set
            {
                if (_title != value)
                {
                    _title = value;
                    OnPropertyChanged("Title");
                }
            }
        }
        private string _title;
    
        [DataMember]
        public int CircularId
        {
            get { return _circularId; }
            set
            {
                if (_circularId != value)
                {
                    ChangeTracker.RecordOriginalValue("CircularId", _circularId);
                    if (!IsDeserializing)
                    {
                        if (Circular != null && Circular.Id != value)
                        {
                            Circular = null;
                        }
                    }
                    _circularId = value;
                    OnPropertyChanged("CircularId");
                }
            }
        }
        private int _circularId;
    
        [DataMember]
        public bool IsEnable
        {
            get { return _isEnable; }
            set
            {
                if (_isEnable != value)
                {
                    _isEnable = value;
                    OnPropertyChanged("IsEnable");
                }
            }
        }
        private bool _isEnable;
    
        [DataMember]
        public string CreatedBy
        {
            get { return _createdBy; }
            set
            {
                if (_createdBy != value)
                {
                    _createdBy = value;
                    OnPropertyChanged("CreatedBy");
                }
            }
        }
        private string _createdBy;
    
        [DataMember]
        public Nullable<System.DateTime> CreatedDate
        {
            get { return _createdDate; }
            set
            {
                if (_createdDate != value)
                {
                    _createdDate = value;
                    OnPropertyChanged("CreatedDate");
                }
            }
        }
        private Nullable<System.DateTime> _createdDate;
    
        [DataMember]
        public string UpdatedBy
        {
            get { return _updatedBy; }
            set
            {
                if (_updatedBy != value)
                {
                    _updatedBy = value;
                    OnPropertyChanged("UpdatedBy");
                }
            }
        }
        private string _updatedBy;
    
        [DataMember]
        public Nullable<System.DateTime> UpdatedDate
        {
            get { return _updatedDate; }
            set
            {
                if (_updatedDate != value)
                {
                    _updatedDate = value;
                    OnPropertyChanged("UpdatedDate");
                }
            }
        }
        private Nullable<System.DateTime> _updatedDate;
    
        [DataMember]
        public Nullable<int> Credit
        {
            get { return _credit; }
            set
            {
                if (_credit != value)
                {
                    _credit = value;
                    OnPropertyChanged("Credit");
                }
            }
        }
        private Nullable<int> _credit;
    
        [DataMember]
        public Nullable<int> DurationInMnth
        {
            get { return _durationInMnth; }
            set
            {
                if (_durationInMnth != value)
                {
                    _durationInMnth = value;
                    OnPropertyChanged("DurationInMnth");
                }
            }
        }
        private Nullable<int> _durationInMnth;
    
        [DataMember]
        public Nullable<int> NoOfTeacher
        {
            get { return _noOfTeacher; }
            set
            {
                if (_noOfTeacher != value)
                {
                    _noOfTeacher = value;
                    OnPropertyChanged("NoOfTeacher");
                }
            }
        }
        private Nullable<int> _noOfTeacher;
    
        [DataMember]
        public Nullable<int> NoOfMaleStudent
        {
            get { return _noOfMaleStudent; }
            set
            {
                if (_noOfMaleStudent != value)
                {
                    _noOfMaleStudent = value;
                    OnPropertyChanged("NoOfMaleStudent");
                }
            }
        }
        private Nullable<int> _noOfMaleStudent;
    
        [DataMember]
        public Nullable<int> NoOfFemaleStudent
        {
            get { return _noOfFemaleStudent; }
            set
            {
                if (_noOfFemaleStudent != value)
                {
                    _noOfFemaleStudent = value;
                    OnPropertyChanged("NoOfFemaleStudent");
                }
            }
        }
        private Nullable<int> _noOfFemaleStudent;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Circular Circular
        {
            get { return _circular; }
            set
            {
                if (!ReferenceEquals(_circular, value))
                {
                    var previousValue = _circular;
                    _circular = value;
                    FixupCircular(previousValue);
                    OnNavigationPropertyChanged("Circular");
                }
            }
        }
        private Circular _circular;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Circular = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupCircular(Circular previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Subjects.Contains(this))
            {
                previousValue.Subjects.Remove(this);
            }
    
            if (Circular != null)
            {
                if (!Circular.Subjects.Contains(this))
                {
                    Circular.Subjects.Add(this);
                }
    
                CircularId = Circular.Id;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Circular")
                    && (ChangeTracker.OriginalValues["Circular"] == Circular))
                {
                    ChangeTracker.OriginalValues.Remove("Circular");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Circular", previousValue);
                }
                if (Circular != null && !Circular.ChangeTracker.ChangeTrackingEnabled)
                {
                    Circular.StartTracking();
                }
            }
        }

        #endregion
    }
}
