//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EduEnginee.Areas.Admission.Models
{
    public partial class Subject
    {
        public int Id { get; set; }
        public int CircularId { get; set; }
        public bool IsEnable { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<int> DurationInMnth { get; set; }
        public Nullable<int> NoOfTeacher { get; set; }
        public Nullable<int> NoOfMaleStudent { get; set; }
        public Nullable<int> NoOfFemaleStudent { get; set; }
    
        public virtual Circular Circular { get; set; }
    }
    
}
